"""
Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:

Triangle      T_n = n (n + 1) / 2       1, 3, 6, 10, 15, ...
Pentagonal    P_n = n (3n - 1) / 2      1, 5, 12, 22, 35, ...
Hexagonal     H_n = n (2n - 1)          1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from itertools import count, ifilter, islice
from problem044 import is_pentagonal


def hexagonal_numbers():
    """
    >>> list(islice(hexagonal_numbers(), 5))
    [1, 6, 15, 28, 45]
    """
    return (n * (2 * n - 1) for n in count(1))


def main():
    """
    >>> main()
    1533776805
    """
    # every second triangle number is also a hexagonal number
    # and every hexagonal number is also a triangle number =>
    # we generate only hexagonal numbers
    print(next(islice(ifilter(is_pentagonal, hexagonal_numbers()), 2, 3)))


if __name__ == "__main__":
    import doctest
    doctest.testmod()
