from itertools import dropwhile
"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def triangles():
    t, i = 0, 1
    while True:
        yield t
        t, i = t+i, i+1
        pass
    pass

def num_of_divisors(n):
    return 1 + 2 * len(filter(lambda x: n % x == 0, range(2, int(n**0.5 + 1))))
    pass

print next(dropwhile(lambda n: num_of_divisors(n) < 500, triangles()))
